### PR TITLE
convert 'tostring' to 'tobytes' in png.py

### PR DESCRIPTION
**Pull request by spencerlepine**
Error: AttributeError: 'array.array' object has no attribute 'tostring'

Replaced tostring() with tobytes() - Now works with Python 3.9.1.

### CODE REVIEW

**Comment by spencerlepine** [comment]
png.py contains several lines with 'tostring()' still. I only changed ONE of these lines.
No errors appeared, but you might want to replace the remaining 'tostring()' uses.
